spring:
  devtools:
    restart:
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    date-format: yyyyy-MM-dd
  #配置数据源信息
  datasource:
    url: jdbc:mysql://192.168.3.137:3306/javatest?useUnicode=true&characterEncoding=utf-8
    username: sms_user
    password: sms_platform
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

resource:
  imageServer: http://image.qf.com
  emailServer: http://email.qf.com

logging:
  level:
    root: info
##file:

